export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const FAILURE_DEPLOY = "FAILURE_DEPLOY";
export const FAILURE_USER_DATA = "FAILURE_USER_DATA";
export const REQUEST_USER_DATA = "REQUEST_USER_DATA";
export const SUCCESS_USER_DATA = "SUCCESS_USER_DATA";

export const IS_VERIFIED = "IS_VERIFIED";
export const CHECK_VERIFIED = "CHECK_VERIFIED";
export const SET_FEEDBACK_SUCCESS = "SET_FEEDBACK_SUCCESS";
export const SET_FEEDBACK_FAILURE = "SET_FEEDBACK_FAILURE";

export const REQUEST_FEEDBACK = "REQUEST_FEEDBACK";
export const RESET_FEEDBACK = "RESET_FEEDBACK";

export const REQUEST_CREATE_PROFILE = "REQUEST_CREATE_PROFILE";
export const SUCCESS_CREATE_PROFILE = "SUCCESS_CREATE_PROFILE";
export const FAILURE_CREATE_PROFILE = "FAILURE_CREATE_PROFILE";
